tuxedo_vagrant.zip : install_tux.sh README.md Vagrantfile \
			../installers/tuxedo.vagrant \
			../installers/tuxedo12.1.3.rsp.template \
			../installers/tuxedo12.1.3_silent_install.sh.template \
			../installers/fix_locations.sh
	zip $@ $^

