tuxedo_docker.zip: build.sh Dockerfile dockTuxedo.sh README.md \
			../installers/tuxedo.docker \
			../installers/tuxedo12.1.3.rsp.template \
			../installers/tuxedo12.1.3_silent_install.sh.template \
			../installers/fix_locations.sh ../installers/simpapp_runme.sh \
			../installers/start_tlisten.sh
	zip -j $@ $^

